language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  api_key:
    secure: TtrvIRVlCumTZJLZ+ykNeAyzVNZ4m7GHj52RNboXgn8glOZqAuMyKaq2QrZozIKCHa1lVB1IbEmaCfJDJjtfWWpZDN3lGJSlkfP4yd4vbOslVjknoIfQir0qGJMBool0ulH4S51I5G6Nz+AVW18WosPcZuuDdruNxdkOV5s2rJqprZ9Gg7dtmciMkrE3Pj2g2ErH9Qm9Jw61LeZ+ULLeNvFGcANsQQQg6wJqpzFGuSDD497OrA03Duqj3jU9Ecvp1orH9WCOXrF5VhjZjVnBKNC6ZulgLqSr/WKDmY/4ntMR+Qp0WxOqAz+j3OkQNYXmXYjshO6bZAfEeK2+WI4jw6MtJQBMGDJBVYrEFyP08NWwRNRLmoJvhMxE+PCrUqovMsjvngrs6P7+7cJnX/8mOLw4DZNdnOVbTNAtr8neBG3XciA2zIu8gIS8JrV2OoCCSxDKlsb+kxF2bBNo6BdGXZzyG6G7yfKUYjrFy5Ha4HVowSm36t8i3dSB4ko0/Xv441XUJn8Abz+/tBSpp0v4BA8UfT6UQCyfPC+He1+XJmdAj6gcq5arP3qZxSTFiO1O66zIwIUTDcDku8oFTiwQmHk4Fj1RbKMT+lIO7K4WFDfYIgg+KWGZjvuA9+vtofXOPP8jhFR7EMT3J89Pe8Kb2oc+ESWCtCMG6Q2o2sRfy50=
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
