language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  api_key:
    secure: bMCpi9eChOUJjZaOjN0oO7qcHOh9UvsTar6EhVr7NckHibTzkuOLWmDbLGKfp9RjWhqKuysEzMs0A7bGS6povYF28tp7txO6hbjI2hRxhd9+gFS4LEFikHi02usc3HhQOYMmsx6ZN/F2C6fx7pfV013sbog3/YccxebzCK2PzsgGebIZuufrzjosf3ewXok52J7YgN2QOIusL4kpWE+7mA1E1Z6My/Lw51SZbafZhciqApziinZ1OLT37tYRtI0Lesl+8/LCGzmLkls3e/Y27Y7eP1osWHAZmARfxUUepkxhJWoWSJxO099QdAu1lEYGk2MD6wo8JZ5cPUCnQtCuhrnH/wVdzg/WBI78oBAWnSET4Rwzv29C9Pj01+HTKe6NoYrYzuQcTSdgDZDBiGGirsKbDlCfhvMXdSh/7VC/TvOYNIOFJFfs/NNJItPMNeQ2csDSM21dAVVYXysY/CxvfGwhbKNZha/9uBUF9wuRa9C1hoS5sbJvuTKJcf7/T3524vpxljyvJChtWlYDgzFboRpog0Bw1oHptdo99CzgyuuE4gDy4ooLdUqF0KL48lqkr7D/xzbZ2DA6ubNl6weDf7BbThaCaQSz6W5jnmx//yBAfIGYnrfyLcxFv0hipJXXwLRHJprEp7w6VcmcJ9wEm7Sbg43JnSQu2SocUvGf82M=
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
