language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
  api_key:
    secure: qWpXYaEa5186QkDNOtFR+kIEG7FCEu5ZtqrcJpTngwlXreKlxSYWg0+Qm9nDgsOK1DhHK6r7QCjk+z74KokuSFl1wM35EwynotQ81g+60+/mrbMu1PoYi5ccuPoYI48gBos233Q9I0MIAlFzzhNbvFFFcpPlO3A3asPhGL49O41hu25QEAYdzr2Xr8rELxb03i24Km0+VG7NCwd0Dshsh+eUo9Bn3bDpb8lkk8eB1gfTao+y9ULbQ3yhTh/b3yD7lcpQEu8fSpwvCPVYTG9h79WoSdZ0ZkYatJVWIxcPRYRPytb7iVWE8VLFGOjFh2zjpDP8+zQuEhNy3fwzbuYZ5pFLdoKrn09NNGSXt2AdaRYJ8SgqhJlUCwbNamZ3m4OcTx4RKXiSnvshqvweM9+QySpQnbJQSG4ByydxathO6+i6LzsaK1MpnCm5jC/u0niqqeGamtqEZDpr4nMn/y6vOXd2R2jJqiww7Fohmt9ybwDonfpwMeudHx0Q591x/KHs1Q5D+lA6eh9mmbu9JTVO84RWlK5M17uzEZG0I9Wy6VZFzgfa9jYnScT7x52vyXB9JtvhJYbHDvw4vYudjfdPPqwfo9aRvZoaht2RMNTxuO5lwJRTRyYxRgazwb1fEDgL5u1Rw+PvXNRqoJsoyElqv6myvrCdcP4wCKLImGXqmMA=
