language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
  api_key:
    secure: ZEqy24N74XjcxZQj79lQCtiqyzbVViDYU/mM+nwI6fxwDKEc0D82dehHTD1U0m5g/eYCMDVN5S0MTBFov4vicT1YSvRgbtLTph5ZKL0Tjj2VUv7zvXTd4KvHLY8lDwaqKuYKIqmxFG00AGa4h4jSr9O1r5GDNJXYw8SBlp3otYGHjo/p2uYsd4gFt2FOXWnFfTfuEX0KlOo888StFD0+dznRm6F9M9RS0zvqyd+CoNP06Q855SvzfLt3sA//1do/QlQZIWCg21HUTIkgsydrTOLAZ0MRRYlahm+Q9ALCCTE6R/sX/OrYqS5WX4ILD7ItXugcSGaixseNUtNjfrkMxXaXCzh7v5lMq+byD+QFNYJk9hFRF1LrSMPYV4wR6Qzjk6UZFp6SECVvVhmd2bYQPZ4ynysk08KZYPKwrCUNGgAKly3nS/6IsZjGFLWpgHWohlzetEP6riCykgc2Ph74TDxNbgkS6AJOLGEQbQXNrQWJ7LaC+SSFCmbpYPvx9prNK8RKMtOJi2EbFs0JE1vNGSK3RYHG7NNxFkW7x4J/b9jtvVMenQUGWGiLTpTlzDG+I4l+yt+OdQK/anjuxo5leglk+gMF994ed+MdXbDgcoRr9kimGJWxA+3KerDuLzdPCztlSB4d/Vsg2RGrfjy0rL1NaVQvfJttgcLdN9zQGog=
