language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  api_key:
    secure: WeOhLkmIGepqpT0sDmC1y9PSYp66TGuwIRmojuukcMGC/BZWn2JHzP5F6aqhbYwH6xGgGHQL5Qw1TPvkjBFZTLYwjrJ8DVjbv8LEntAET4pmeNhVZaJug0cVW3Zejj2Er6+f4GLnFhSawd4QVph1ioYVXHuQaxGdqPseVj4p/2WUGhTlnGYbyItAbyb5H/rin3UHNRxWV4nq/Pmjl8nHO9uu+OIiFWdkhESSC1RNzsA9S+oR2bvENQu+1Wm0nFb9cg9ILsQPrTKaX0KM/fqB1pNrNE6YOTh4CsZeZsI8EVhXEgshduhWpyDdBch+rVwrOiu5aukATKB7qSUYlmhsDeGT/KBvpsnhzSkgX17NMoLON2pwNdR2Q/fSMJ0aZhwBbupXv4RNwpUBZuZMeSfR9OqyYo1pia7YrOUW+VDQiBGNNjl3m4wimTit0sLnPwcVwXUdXJJXPcj4nFDFfWi8Z9T7aQr7RiBGpOJQD/Ne1SFgvLAx9JRlnEbVrYRu0bi7IhDeBN1XKqI2R4awf9C31KfRNkJ3aO74N+zhtwweT51yohRDsmIqEsG+OeDUtd0PPCXZv6bZVUMu2JDiDhAgdz0Bo0SJ8W0+K/ljdmYI9RA2UbXTuIRAfENdT/aKYgUMiDC3Fda4dxyhJ8heeeylDWbbsNS4MK3TfpFOsiEQtvU=
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
