language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  api_key:
    secure: Dh7ms7P6YoYGcKLqX+hfEz9ckXiCIb0sEgbXXnyzGk9jdJ+IoU5jegh2Cnz/UkH60FfSBBKtD7kxo+NEW46Eyia0FjULYaQTr6E7uNnoMzvhJIoAseHwu0/D2JYrPXMOCbtThexZQA5eKwEtLalfzurGoGpHvVMBGMmOTjZ1hfHn6DdYoKVQ5mID1QlTCECG5f3fcM/lXGHPwbaM91fBlKNyJ1DaTe8G4QCXZhkJ+KEMrn/lBgbVEcQUNsEUuc+WwQb/l1FukJVGzp2fyNjuW8Q471HHUiEY4ko+zEo4dNFkBW3md7lhRL2EHsJP/QGJVJHVeH4sbcbXBwWSKRRriG6qg6tQsnQ02Oure+uCo0pqMC8yw+JWEK3koQeMDjho2SbcWE+7csGLVbGTedjs7J+W5P4Tp4KZuJlUgSqr4kjxP6zjt483jC7SRTvmcbFwo/U5eXI3I7h5elxvcaMEDWBvKCliYr4SbH4mZBO8ZaQ0DxMe0W3nnr5a75byosDj2mEEhj+vFrDS1PKJRhi19z8t4xVcP2CoiLqd+G3W6DEM7wDmUJcnKQHPRGyBfil/tsqfbQtVc5rh5+xlh7mWO2fpuLhwliKx5Mj6zKUKyn5fEbL99fddyZddcEeYqC/tBQ1hXp6X7pFh7H0j7nAywk/gjzSdiYJwWwxjkKmj2Kw=
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
