language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  api_key:
    secure: LOZ9r8KcjoOvp1q9XA9ZbWbTanf0oAj5ScsK7Cmnj4m0UraJn6kv6gGV3V5BvYQ8TE1ATkEEQj6xSepjABLjbHxDNZxo8eqAwp5NkLqddQ/2woF5OMcXkAqYoeXFYYbiJrt6SXsNdqRqxIJG7LCvHMwUgLF6Q71fMgZ1C1UK40DP7lq2VK1/oljmPFFnSpNcdMm8LXk68N/qQIjuFdEeAePbEKPk5sDMfU4op39TyWfJxwsNKiJkVehpmYpl5ISRdg0FNoMa7+2uQlyEXIUuQnep82NdYbSYPUJTkkKdWilDvOXPbz6Ie6t6WKFjUpD4Q98Q52W1ld3MG4pr37ls0QGIkofuoaK/l3zPKpkJ/tSxZkWL4iWNKZzmys1yQzQUB4D0z22z2v/y8LuGBeOx1u0c+CC3s9Axk+Wgzt+4h1sgLVldo4eo8CNinHXc7YyBsrHSLAv3klT//GILF47sH38iQuBMXHXtqUnuF42ZPEg/gACrYxH/a0s6mWB4La785AF13QU1SJln3ag+bIYDBxKl2w6mlL7RwdM1+V3iUDLlwibRAEeNmpoMIGV3/I8vMkdNMkDmIVUn/1Xw+xvHO7Vs+PuG41j0ZcCuN3ERhUr90PryR9P1X2lYbm4vu1x2MrlHaa7s4udLsVA2fmUff00+7E/McWl1RLyZbp7EPK0=
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
