language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  api_key:
    secure: EcYmqL9GeuCi6KDJ9LDapUV6G7JV0Ok1J5nV5sCkFgRXZDdyicUGucPRlIJEoAdDOoryvgibE2Kl2Y46vbqdA1oWhHSYmUJbtCaM2TtkyDEFn2jv8WX84cGxw31oz80uXsZw2wO4QUufhZPLnVrN28JpzEClGIRiyprqvoIer8cimdKjltVw7gHPF+PKcbT2DFuAcykw4aoIwNOpG0MUrWyid5WWZvKGl7TmJJhCOpQ/ZwYA1s+gqWlz/0gqsd8h6vO1MnNi/qLqJN/wQwbpJmYGtJnIatHkNucUtfRAyqWuGE84ar0X4iiDWl/aS2OzGgf2hLryVq6OMNzj58uTqSF2pOTBWW9basLmzo8UkWFnc3viJ0gbf6qeN219GewlIlK5U3V7TwjE0SYr0YM2HUl+YPHRDQshkPRGqhKdMaPNeJNZKCH5RBvue0530UTWup4172ki3IrjIIEz3mQxzJ/RCZGzlTT+dxYgeUI3OORW4WDkmDVKb9gdlHwWvfHwQeyLzsiDK2XnnVjjuVSBbvHZSYQxe0jC8bZ7KuIRniPxt0oqra6CXn1+qZoBUfZEKxcBTwcKbU2g8K83g98tqYGQ22hVCY+n1hzowfHxwgO2LtHV43G2Qn9eAqJcoG0Vlvqf84bBIWbdpqzu1yOulbCiWdKO28k9ZrvKpRDeAlc=
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
dd:
  secure: cibjrdYtXOPAmacWZLNTugI7DCAVYFjlgktBzZTeU5Uyw3/CcfQ26kmtJnkAMynPyrri34wraopXPbs93OGXn358ZRqhPNG00VYL9H2m2W4Vpf3Y+9um83x0uiCtor7sD4t36EfGvynYBDkFACb+dQOe4fYxxfdAd7T9IipUBRJsoOqIHiSiKooSkkQ6mDV0XicrSx5Kw+9URYua2gAoxRtfc+fBqY8X5JeDAWtYM/gUVmXLwsGH3PfgZeqgA6V62aQW6+4bZclJr15rFNdmbNwq5ZEHQ+pkwqUlJTO+vF/5mJdPBc+GTZDRMdejtbcqMdQHctpcG//gQxRkWPD8l2/i2StKUDAUqF23erqtThamGDlaYJXrpl6kPWc7UrslWOXMmNGsL0G5B+jxWfWGRXAt6u0rGg7Y4gqa6SCKq8+FCyBEU3HTyDjD+Na0kUllvgGMa5WXN87DduNkKVxamy/GrcyE7qMETm6yP6EypdyfQUotqUxX1GTKmBYchEibKM29BJZzi48gBdH2EPuUtebjnb/YK0Wmf5FZqvboKhKvrkaKtJ2f3Y/cN3Bs6Aa/a70jqQurZLu54kLHtrKbQIRXA5yyaBOLNEmX40JF+fZI1Uh6PqWsYgOUHQ3luWbcrm2XkdQJckoL4ySY/WLYfL792huRzvg4PnLyI+PMXO8=
