language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  api_key:
    secure: EcYmqL9GeuCi6KDJ9LDapUV6G7JV0Ok1J5nV5sCkFgRXZDdyicUGucPRlIJEoAdDOoryvgibE2Kl2Y46vbqdA1oWhHSYmUJbtCaM2TtkyDEFn2jv8WX84cGxw31oz80uXsZw2wO4QUufhZPLnVrN28JpzEClGIRiyprqvoIer8cimdKjltVw7gHPF+PKcbT2DFuAcykw4aoIwNOpG0MUrWyid5WWZvKGl7TmJJhCOpQ/ZwYA1s+gqWlz/0gqsd8h6vO1MnNi/qLqJN/wQwbpJmYGtJnIatHkNucUtfRAyqWuGE84ar0X4iiDWl/aS2OzGgf2hLryVq6OMNzj58uTqSF2pOTBWW9basLmzo8UkWFnc3viJ0gbf6qeN219GewlIlK5U3V7TwjE0SYr0YM2HUl+YPHRDQshkPRGqhKdMaPNeJNZKCH5RBvue0530UTWup4172ki3IrjIIEz3mQxzJ/RCZGzlTT+dxYgeUI3OORW4WDkmDVKb9gdlHwWvfHwQeyLzsiDK2XnnVjjuVSBbvHZSYQxe0jC8bZ7KuIRniPxt0oqra6CXn1+qZoBUfZEKxcBTwcKbU2g8K83g98tqYGQ22hVCY+n1hzowfHxwgO2LtHV43G2Qn9eAqJcoG0Vlvqf84bBIWbdpqzu1yOulbCiWdKO28k9ZrvKpRDeAlc=
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
