language: node_js
node_js:
- node
cache: npm
script: cd frontend/booken npm run build
before_deploy: cd ../../backend/flask-api
deploy:
  provider: heroku
  api_key:
    secure: dtoAr0qjM3th7w932KDWuEYjxfi0Ynk01CeMfU4M/KJuIejeV9h38oSvQduy5BH9jv8TTCYvJ9oaqsGGL5qVZK3+UXxOtDqDfTLlYIjhcb0x1OKt8h34FpeXAukP6kbEw/VfoaQMaAFbkl+gFti7c8m5u6Cnv9m2aS2GUE+tX/kIjyTPinVgMPeKU0r35o5vyOKzA8fCS9okPKfAyoYrLwb95Oi9f37Vh7f4+gQdvcrpAaPTnI22GHXp/+V91ceoFbURvISHwuPtffRJBuHEobyX3AEqCGHBAEnUGJXDfy64JpxiB8d2Dq29RMuSK2rjzMyYoT8FK3sK5h+zCcZpD74NjyPw7rETTw4FqCOVVtEPu+F6DOB8VUZ2KqRjukbFShho0ZAtO5kfdenidD9R8/km0CA2Ofj8Fb3HjnEWVcS8CW9cv85BNSM0JxPa6OK+zsMODojn68sYDsA52vuO6UjfSZDJzK2MW2m5Y1XLqQAAUu/ghLZGVQmMu9jSrM8FR0AUrl40XoWJ0AjtUJAQEG2IC9mR3qHNMucH05V2LPeJknTw+smj4y9SrWWD8wOivRkLc0Q9nH2u0YdsblDw28t3Oqg53qdfyujoKp+4hz4FOL1zlW1AY1CjIUMSBHl8jVggHOCZp0PFrg9IjIHFnB/wtp5UmTwpPnmdWhdCAW4=
  app: booken-app
  on:
    repo: UB-ES-2020/Booken
    branch: development
