language: node_js
sudo: required
node_js:
- node
cache: npm
install:
- npm install newman
script:
- cd frontend/booken
- npm install
- npm run build
before_deploy:
- "./before_deploy.sh"
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: Tbtne+5uUQ+oCA8D5LXqZA0+BRbFRfJ2P29urU+Vl1dFAK6jfB1md6xmaI3GsiByu3jgt8wmZ04xKlkqlhsHO9OjzD5OomJFqc3rTeAyX9zgT3ed2Jufp/19/HoN614n8SFFA0uWF9tDwjfiARWyHlflOaXFHGJDlgQJ/jLEVwIZ4OZKmxAownD8f0YsyLXBc2TJimJEed0xNVWkU5CnNsrs/oYZdfzgadkoVP31X1CqthaZ/cxZouG0/nIDYe/jlj1kzY9X1rSPakPl1UTpMMqs4gTDPlo5PGAwdiMEcw0j9FZFF3c3QUVcg4M0AkvjeYhR5HRnDHf7rtoXHG3D07m3GgLKOx6VQdSporGH3Acz7j54JiP5y4kYDaj3geLgJIVA/Eh6Dv8PXCwnd9J30ZExVSpc8Vhoc+FeVvwQ2cqFLKZNz7punCTB8BDM8No9jcNlGNxtRXkS4kB8dHu2xmZ+7XYV8pHohI+cZYxT5II7Z6WOrcgIzES0xgj4oBP1wl3HPJ8lQcPYSdJa7N1+b8sm+Kg4M7BTBRzBvOlwvpAQhftGHaKRWJfp8fOvAmbnkEL70I/0Hldr57tBq/yBKcHjQBlifDRmhj5sAjk494HCrsQdGojj6345VUzckZoSRU4DqqbR/h9dm9K8MDojvyju1ThrtoHPXgbZFf0l8N0=
  app: booken-dev
  on:
    repo: UB-ES-2020/Booken
    branch: dev
notifications:
  slack:
    secure: PmiwCTDDv9GxdBKDQWIJuB/jmOxEvU7aW0NhOBuCAJ2G77pxt7zTCu9kJS2TtziiUEPwTCe7HmkiTB0xvykoTipaN4UOpN6INMgDwl4jd4bbCB8IabJsY8RVCmXbpbdotJclkS5Ul/XLQN+G7RzsFbLiniZ3d1X+V82JoAajT9CCuk1FlfVDhuh3EURbcqD7HqO26hhoKSQepqDSlAAqLKY63ScIQHguEC1CovBuWd6W0OiE5UnTxm7aA3WR+fId0q+OZ5oAbJahwRVNC37OFYwSjGkBscB/FK9MrtRPl5N2jW8tEzg8lmbROchZawH04o4j5nxsjpeNunOIJD9ZOp65PHyot0qZTDPEsTID86s9f90YYqqYtBPXILtGqLPK2Yjdb2xkIJ8xjmZ85PG3OznqzgojGhauK7VVzdmoiyoPHoGtwIZj1dlUOYYUJ1SLJPvF2Mqu9W5SGSh9jqMq61NgSsgeNi22LVH/Sf4cmt8cyuQvruRElu9K/JZrfmiApSPg/ypsTvy+UBdCqiFhhzZnKEMxngph25zlcAD4uRGnGEvbIJpsZdI5IcYfBNCm5MbuVjRjfC2PjuAufYVz0lUaObBp27SCILkB3tDyk3kjs0UCtIfj3BWE55Nme6qXl/z6zSO7c5l48xWkuxuRRwnsHmkk2DUAs9aLPwwK4QI=
after_deploy:
- "./after_deploy.sh"
env:
  global:
  - secure: awECUcH/jqBDhnAi1ccNw+qNYCyMQmRtEo5L1dqNurHb4Ex4dW9nYazXHKWR329cgH7dl7vGbvJEpRnQzCXXJAVyB7KA43BbVy+qTPWyKkuskPxljF4q16l6yfcz8CIsesZraJrUT7P1q5XFJHnMKczwggS0Ob7QcnMGjIqdiPgDpuO7irr6UH2ockFkX15cj77+TIzivuabMOoSr2omxPhZCMV3gh/VxZ58KMFLAn+BEU0QcS/4dVNN1RoNHK6qegzrxP2oy7ZnUBN4uuBrlEnX04CKgOY1ak/P60G+OOJip+G4sE9yUNsl8uD541MsvzcVYy2JbG06iJbAPbFUEuin1F1KPMuUwmEDw941lj9fAnsAO60JMF3PJF0wXR88DljmlRCdtZje9TmLxC0wREHCog7htq6N0s803JURDqdSRIV/S90G5cFT2D4VgBotkRrhlANN8Jjk7zbDL05NUUmnOwoJ1e1J+tsRDegEzXHOPnIUtdDN1WO6SuCA45NwHJmQujCLAz36cxD7NmB1Y0dS2GNOz9m9/BIos1nRcjWzjDWU5TIGpCQ3WMZiK6EZheEY3q2U0hTcIoSR5WNao3v7JQZnO6/tLz6qqM7Fh+Fr41mNW2GflNJumloTXegSpsHm1pE12gnpH1hzgiRiAhSceFDmEMKoX0KQ7IGQbnQ=
  - secure: oq4AXbbPaFMLPys0k2wPYwX0rr1/6AB4EhylJAkB1HEcx+7b8Cy94H4u10IIVY5X/L0YBPIHzM+pnb4LkSTWSuXFUgpmhDjWcUhgcfHHOugKfzVuQ/kNlx/wVgsbaPKen0sTqG4rP8JAB+8Ef0dq6YyP7kQgO7NBf7NQyJrwXgfjojxA94Te6BiTKIpOLcpwJ6NmNCShR/kUrUWFRZKbSg5CtTSqugCK17UlszWzKFZJ2rt1rwB9G2n4zz8tFyDRmbvsClVCGdqIvuA96a5Z6L4WUflHjJuJD+JGaZGjMJgvypry6ilJdvEC7JfmowQZluaax6J/w3EnSDFpPofIQCh0RELdcoUkAfB5PsTa4+sB5aFw4l5AsdZvziGmEHhOyG3vulq6nQT2HKVaLZuunTZ5Cf8nTKPSN74M7BTidNjIc5VDth/7IsqK1YlbxFrC3xrCqtJWDm2GtleqADkOkJ7sI4lMA8Ob0fwLdnh+7tNMMEdD/tqPM2kEEMVdg7VsxBX1TX96WHJe9CBuAxf177vCHhFHrchTEAoYH1Pp4iQ21oYabMEC1g0cZttZ8Oa4Kaa7hVgcmW2vmT/Z/cDi/PPP3TJJwimCR81BGRvzCXpFcwcnwQ0yW7qlUVXMLgejs7gsYwA6tBGsD7Hcb9Sc00PwqtNauMK+KWs40rXx+4M=
