language: node_js
node_js:
- node
cache: npm
install:
- npm install newman
stages:
- name: build_deploy
  if: "(branch = dev)"
- name: release
  if: "(branch = main)"
- name: code_analysis
  if: "(branch = ca)"
- name: build
  if: "(branch != dev AND branch != main AND branch != ca)"
jobs:
  include:
  - stage: build_deploy
    name: Dev deployment
    script:
    - cd frontend/booken
    - npm install
    - npm run build
    before_deploy:
    - cd ../../backend/flask-api
    on:
      repo: UB-ES-2020-A/Booken
    branches:
      only:
      - dev
    deploy:
      provider: heroku
      api_key:
        secure: U2RgOl4ilgVLVvV8Rr9RQ2sgOW/NxP/O/A3soFWyXTARgeJkSk0qRaPUVkvpcbGlycw2t8ANmpMObUVMCSNmIngydLutFomcbgjOp3MkU2DjKIVdaLc9iuCE922BSVuJCRXjv1r+uwnCve2ba+xIi8piUTeQEakSLiZSaJPFZH068YV/xOSnmg7TsILOhA3c77vSii296rFCSFbRBLt8xTAtqMZrC5UEzN1t91K3vpRXICfavZIu7KeFjr5xLO8d2H9+yYgghXdXmn0cxn1zcnH5XJ8jJDsNsb3IithPGCcm99lzSkp5WugOWs+fCmG9YwRfECtailrv/gmNul0aho7cULzgEVOR93oUPE+040ewYssdXMM5yYffgRtaxVs3eNu4OgQAtriAJvM6/Gwfil/vslJRrf/Yrew5ezdzvqSZ6O8EbBTHG8FL/p0Myd6inT5qUVzJvaLwOv0MDQ3rEgaPa8cJc/em0dWq5W7HDilxn665jQiLgx7m7/cYdqlmfPgQiFFsfpTnGNHza26tidp1f61w/2yzkb2S56EBl6JbYKvUIIKMs4lITg+qhJSBv3CBUl/fQqOkRmcd2ciEDM5+tR3iYREqH5sxKTdX2B49HHx0bL4gMaDW1I4QRfAGcTNsaC6xuKx7qXb4ueDTIath7E/xtBCUJ7fgJgroXzQ=
      app:
        dev: booken-dev
      after_deploy:
      - cd ../..
      - node_modules/.bin/newman run backend/tests/TEST----Account-Login.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Author.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Book.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Reviews.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Address.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Card.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Orders.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Articles.postman_collection.json
  - stage: release
    name: Production deployment
    script:
    - cd frontend/booken
    - npm install
    - npm run build
    before_deploy:
    - cd ../../backend/flask-api
    on:
      repo: UB-ES-2020-A/Booken
    branches:
      only:
      - main
    deploy:
      provider: heroku
      api_key:
        secure: U2RgOl4ilgVLVvV8Rr9RQ2sgOW/NxP/O/A3soFWyXTARgeJkSk0qRaPUVkvpcbGlycw2t8ANmpMObUVMCSNmIngydLutFomcbgjOp3MkU2DjKIVdaLc9iuCE922BSVuJCRXjv1r+uwnCve2ba+xIi8piUTeQEakSLiZSaJPFZH068YV/xOSnmg7TsILOhA3c77vSii296rFCSFbRBLt8xTAtqMZrC5UEzN1t91K3vpRXICfavZIu7KeFjr5xLO8d2H9+yYgghXdXmn0cxn1zcnH5XJ8jJDsNsb3IithPGCcm99lzSkp5WugOWs+fCmG9YwRfECtailrv/gmNul0aho7cULzgEVOR93oUPE+040ewYssdXMM5yYffgRtaxVs3eNu4OgQAtriAJvM6/Gwfil/vslJRrf/Yrew5ezdzvqSZ6O8EbBTHG8FL/p0Myd6inT5qUVzJvaLwOv0MDQ3rEgaPa8cJc/em0dWq5W7HDilxn665jQiLgx7m7/cYdqlmfPgQiFFsfpTnGNHza26tidp1f61w/2yzkb2S56EBl6JbYKvUIIKMs4lITg+qhJSBv3CBUl/fQqOkRmcd2ciEDM5+tR3iYREqH5sxKTdX2B49HHx0bL4gMaDW1I4QRfAGcTNsaC6xuKx7qXb4ueDTIath7E/xtBCUJ7fgJgroXzQ=
      app:
        dev: booken-app
      after_deploy:
      - cd ../..
      - node_modules/.bin/newman run backend/tests/TEST----Account-Login.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Author.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Book.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Reviews.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Address.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Card.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Orders.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Articles.postman_collection.json
  - stage: code_analysis
    name: Code Analysis SCA/DCA/CC
    script:
    - cd ../../backend/flask-api
    after_success:
    - coveralls
  - stage: build
    name: Project build
    script:
    - cd frontend/booken
    - npm install
    - npm run build
notifications:
  slack:
    secure: aTbGa5ESd04A0MrqCeM+Vc/yzBDjoArQMDWHqsBshhrCh72TP9rUdsoikB7bPW21dggUnmlmmKZeoXD9UYUP0IyY/9i7hTtxh4ijlt9jgdtLmFblZLYWhkndcmMlIfwFknXz2N3rfeRYsem3c74P+9CtcgN4p+DgDF13Ji+g0rKXC+rn/6eB4oGwLwUi+hpB5UgcfTUgsq1HVYK+SX5o4oKZOUbwUcfHFU3BPA8umqXeH0t756z4cObrhFjS+6+fbcN7Awx8ChqSvGV+1morIzVe7jIjwmVurdqitAq9ZWI3E1jLS/qLyfi/vq+D5pY25eMvC3xX2lK09arKz0atBe6GYDuDiZMmMmzApBDSy6BhQuZeeXINrQy0O2aNUmc6TiZ13zT1Pk8d5N0sH6wC06I+pEfCsZUzHBkbQdGK4b3bnMCbnFnCaMPOzQ741ioswxip5ux7b3ts/KQRE4jOiQeOb5qtYJk1qhbXAyaqJT0SfLKdH/nVHhJ6+7OPJX0cRn1GSsRE8RAuNqgzstkSZ8y02jSalZT7gPDNet89K/6VPTseMCiBt2JETQ6bEQB/9cFYfUa3oqUnl+d0iGv4gfDFB4Tsr5wW6HVPt8LY5X/KOi+uyvSI4G9fGlfU4LwQOutp62WsITUrQLUJDbLtIVJ8oFNAuDJmSxUDLuIcEBo=
