language: node_js
node_js:
- node
cache: npm
install:
- npm install newman
stages:
- name: build_deploy
  if: "(branch = dev)"
- name: release
  if: "(branch = main)"
- name: code_analysis
  if: "(branch = ca)"
- name: build
  if: "(branch != dev AND branch != main AND branch != ca)"
jobs:
  include:
  - stage: build_deploy
    name: Dev deployment
    script:
    - cd frontend/booken
    - npm install
    - npm run build
    before_deploy:
    - cd ../../backend/flask-api
    on:
      repo: UB-ES-2020-A/Booken
    branches:
      only:
      - dev
    deploy:
      provider: heroku
      api_key:
        secure: faxQRcuR0Cq7SS4vc5PteV32AF3SB9y+d0qnt1E5+nfNImaeqVAm0/6UFGWdaFn4cc5N87xy4ce/+sRgwFhLKFdlotgEryh26ZvvQqrNFoWcFYl6yTUUPBeeU1X740zz0sjhSTK2vTm+vcSGyeJRJm1P0au5YbrQClPDWFhVYNWWf0w7EuOpFLhgiIia9AmQGQBPXJviNI5yNmd1iJefmhPBp6LZQFgIaqm1EF0EgVsc3O/0uQCIIAvX+SNbzJYE49vA0qoUguMtSBM9EdLEMfniZ3uGMqxgYQ/DYe+DpQtSyt1BMtg8Ae5qBgGC1blBJvejrx4NtAYMt2Yt16iKKgFLJ7UJfS11tlebVWTdBuLBfaecNeB5UbvvEeb9Am/sPIpTKcqLtPnpUiINVQcbw98IrFK8h1Lj1vsVi9KhvfFdERrV2pjMC6YVq86txG5u2GNIR6F24mzhYz1cC23z+ZKs3CYsBUpk79BQ5Lg3Kargm6mn6EXYmEmWdcjCxL4DjtnbTLUWIsoATC0ALB8zMLwKeELVGLbiVGyHqNMZb92Vi1FktIbT97EJk3VN0ar6oIciitPpFpCUfreF/U2n/GeX6ixzYaJM/NkJzsekpTyMMtvv1dLkl9mG1qN3G/ktrQhNLJeoKqMOCunRUya6/MNy89pFfYPPxHvuIfK8iP8=
      app:
        dev: booken-dev
      after_deploy:
      - cd ../..
      - node_modules/.bin/newman run backend/tests/TEST----Account-Login.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Author.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Book.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Reviews.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Address.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Card.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Orders.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Articles.postman_collection.json
  - stage: release
    name: Production deployment
    script:
    - cd frontend/booken
    - npm install
    - npm run build
    before_deploy:
    - cd ../../backend/flask-api
    on:
      repo: UB-ES-2020-A/Booken
    branches:
      only:
      - main
    deploy:
      provider: heroku
      api_key:
        secure: faxQRcuR0Cq7SS4vc5PteV32AF3SB9y+d0qnt1E5+nfNImaeqVAm0/6UFGWdaFn4cc5N87xy4ce/+sRgwFhLKFdlotgEryh26ZvvQqrNFoWcFYl6yTUUPBeeU1X740zz0sjhSTK2vTm+vcSGyeJRJm1P0au5YbrQClPDWFhVYNWWf0w7EuOpFLhgiIia9AmQGQBPXJviNI5yNmd1iJefmhPBp6LZQFgIaqm1EF0EgVsc3O/0uQCIIAvX+SNbzJYE49vA0qoUguMtSBM9EdLEMfniZ3uGMqxgYQ/DYe+DpQtSyt1BMtg8Ae5qBgGC1blBJvejrx4NtAYMt2Yt16iKKgFLJ7UJfS11tlebVWTdBuLBfaecNeB5UbvvEeb9Am/sPIpTKcqLtPnpUiINVQcbw98IrFK8h1Lj1vsVi9KhvfFdERrV2pjMC6YVq86txG5u2GNIR6F24mzhYz1cC23z+ZKs3CYsBUpk79BQ5Lg3Kargm6mn6EXYmEmWdcjCxL4DjtnbTLUWIsoATC0ALB8zMLwKeELVGLbiVGyHqNMZb92Vi1FktIbT97EJk3VN0ar6oIciitPpFpCUfreF/U2n/GeX6ixzYaJM/NkJzsekpTyMMtvv1dLkl9mG1qN3G/ktrQhNLJeoKqMOCunRUya6/MNy89pFfYPPxHvuIfK8iP8=
      app:
        dev: booken-app
      after_deploy:
      - cd ../..
      - node_modules/.bin/newman run backend/tests/TEST----Account-Login.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Author.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Book.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Reviews.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Address.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Card.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Orders.postman_collection.json
      - node_modules/.bin/newman run backend/tests/TEST----Articles.postman_collection.json
  - stage: code_analysis
    name: Code Analysis SCA/DCA/CC
    script:
    - cd ../../backend/flask-api
    after_success:
    - coveralls
  - stage: build
    name: Project build
    script:
    - cd frontend/booken
    - npm install
    - npm run build
notifications:
  slack:
    secure: aTbGa5ESd04A0MrqCeM+Vc/yzBDjoArQMDWHqsBshhrCh72TP9rUdsoikB7bPW21dggUnmlmmKZeoXD9UYUP0IyY/9i7hTtxh4ijlt9jgdtLmFblZLYWhkndcmMlIfwFknXz2N3rfeRYsem3c74P+9CtcgN4p+DgDF13Ji+g0rKXC+rn/6eB4oGwLwUi+hpB5UgcfTUgsq1HVYK+SX5o4oKZOUbwUcfHFU3BPA8umqXeH0t756z4cObrhFjS+6+fbcN7Awx8ChqSvGV+1morIzVe7jIjwmVurdqitAq9ZWI3E1jLS/qLyfi/vq+D5pY25eMvC3xX2lK09arKz0atBe6GYDuDiZMmMmzApBDSy6BhQuZeeXINrQy0O2aNUmc6TiZ13zT1Pk8d5N0sH6wC06I+pEfCsZUzHBkbQdGK4b3bnMCbnFnCaMPOzQ741ioswxip5ux7b3ts/KQRE4jOiQeOb5qtYJk1qhbXAyaqJT0SfLKdH/nVHhJ6+7OPJX0cRn1GSsRE8RAuNqgzstkSZ8y02jSalZT7gPDNet89K/6VPTseMCiBt2JETQ6bEQB/9cFYfUa3oqUnl+d0iGv4gfDFB4Tsr5wW6HVPt8LY5X/KOi+uyvSI4G9fGlfU4LwQOutp62WsITUrQLUJDbLtIVJ8oFNAuDJmSxUDLuIcEBo= 