"""empty message

Revision ID: 18d1f6e26287
Revises: 
Create Date: 2020-11-11 19:59:33.310092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d1f6e26287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('available_money', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('birth_date', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('genre', sa.Enum('HUMANIDADES', 'TECNICO Y FORMACION', 'METODOS DE IDIOMAS', 'LITERATURA', 'INFANTIL', 'COMICS Y MANGA', 'JUVENIL', 'OTRAS CATEGORIAS', name='genres_types'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('editorial', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('synopsis', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('cover_type', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('num_sales', sa.Integer(), nullable=False),
    sa.Column('total_available', sa.Integer(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=100), nullable=True),
    sa.Column('back_cover_image_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('contact_query', sa.String(), nullable=False),
    sa.Column('contact_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('label_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surnames', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('cp', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('telf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.String(length=30), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('shipping', sa.Float(), nullable=False),
    sa.Column('taxes', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('In progress', 'Received', name='states_types'), nullable=False),
    sa.Column('adress', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id', 'date', 'adress')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=False),
    sa.Column('valuation', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('books_id', sa.Integer(), nullable=True),
    sa.Column('authors_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authors_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['books_id'], ['books.id'], )
    )
    op.create_table('relationship',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship')
    op.drop_table('tags')
    op.drop_table('reviews')
    op.drop_table('orders')
    op.drop_table('addresses')
    op.drop_table('contacts')
    op.drop_table('books')
    op.drop_table('authors')
    op.drop_table('articles')
    op.drop_table('accounts')
    # ### end Alembic commands ###
