"""empty message

Revision ID: 2fe6ab7cfb95
Revises: e00cecac7a53
Create Date: 2020-11-13 10:22:01.612917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe6ab7cfb95'
down_revision = 'e00cecac7a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('card_owner', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('payment_method', sa.Enum('VISA', 'MASTER CARD', 'AMERICAN EXPRESS', 'JCB', 'DISCOVER', name='payment_method'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_model')
    # ### end Alembic commands ###
