"""empty message

Revision ID: 3f31d6014ac2
Revises: 
Create Date: 2020-10-22 11:43:04.060903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f31d6014ac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=False),
    sa.Column('genre', sa.Enum('HUMANIDADES', 'TECNICO Y FORMACION', 'METODOS DE IDIOMAS', 'LITERATURA', 'INFANTIL', 'COMICS Y MANGA', 'JUVENIL', 'OTRAS CATEGORIAS', name='genres_types'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('editorial', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('synopsis', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('num_sales', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
