"""empty message

Revision ID: 509271076b7d
Revises: 
Create Date: 2020-11-09 12:42:27.720297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509271076b7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('available_money', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('birth_date', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name', 'birth_date', 'city', 'country'),
    sa.UniqueConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('genre', sa.Enum('HUMANIDADES', 'TECNICO Y FORMACION', 'METODOS DE IDIOMAS', 'LITERATURA', 'INFANTIL', 'COMICS Y MANGA', 'JUVENIL', 'OTRAS CATEGORIAS', name='genres_types'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('editorial', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('synopsis', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('num_pages', sa.Integer(), nullable=False),
    sa.Column('cover_type', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('num_sales', sa.Integer(), nullable=False),
    sa.Column('total_available', sa.Integer(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=100), nullable=True),
    sa.Column('back_cover_image_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('contact_query', sa.String(), nullable=False),
    sa.Column('contact_date', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=30), nullable=False),
    sa.Column('label_name', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surnames', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('cp', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('telf', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('num_books', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('In progress', 'Received', name='states_types'), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['accounts.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('books_id', sa.Integer(), nullable=True),
    sa.Column('authors_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authors_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['books_id'], ['books.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('orders')
    op.drop_table('addresses')
    op.drop_table('contacts')
    op.drop_table('books')
    op.drop_table('authors')
    op.drop_table('accounts')
    # ### end Alembic commands ###
