"""asd

Revision ID: e90560c96f02
Revises: 509271076b7d
Create Date: 2020-11-11 16:44:13.983366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90560c96f02'
down_revision = '509271076b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], )
    )
    op.add_column('orders', sa.Column('adress', sa.String(length=30), nullable=False))
    op.add_column('orders', sa.Column('date', sa.String(length=30), nullable=False))
    op.add_column('orders', sa.Column('id_user', sa.String(length=30), nullable=False))
    op.add_column('orders', sa.Column('shipping', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('taxes', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('total', sa.Float(), nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'accounts', ['id_user'], ['id'])
    op.drop_column('orders', 'id_book')
    op.drop_column('orders', 'num_books')
    op.drop_column('orders', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('email', sa.VARCHAR(length=30), nullable=False))
    op.add_column('orders', sa.Column('num_books', sa.INTEGER(), nullable=False))
    op.add_column('orders', sa.Column('id_book', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'accounts', ['email'], ['email'])
    op.drop_column('orders', 'total')
    op.drop_column('orders', 'taxes')
    op.drop_column('orders', 'shipping')
    op.drop_column('orders', 'id_user')
    op.drop_column('orders', 'date')
    op.drop_column('orders', 'adress')
    op.drop_table('relationship')
    op.drop_table('articles')
    # ### end Alembic commands ###
